/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import { styled } from "@mui/material/styles";

const Points1 = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: "auto",
  width: "fit-content",
});

const Polygon1 = styled("img")({
  height: `30px`,
  width: `30px`,
  margin: `0px`,
});

const Polygon2 = styled("img")({
  height: `30px`,
  width: `31px`,
  margin: `0px 0px 0px 4px`,
});

const Polygon3 = styled("img")({
  height: `30px`,
  width: `30px`,
  margin: `0px 0px 0px 4px`,
});

const Polygon4 = styled("img")({
  height: `30px`,
  width: `31px`,
  margin: `0px 0px 0px 4px`,
});

const Polygon5 = styled("img")({
  height: `30px`,
  width: `30px`,
  margin: `0px 0px 0px 4px`,
});

const Polygon6 = styled("img")({
  height: `30px`,
  width: `30px`,
  margin: `0px 0px 0px 4px`,
});

function Points(props) {
  return (
    <Points1 className={props.className}>
      <Polygon1
        src={"/Points_Polygon_1.png"}
        loading="lazy"
        alt={"Polygon 1"}
      />
      <Polygon2
        src={"/Points_Polygon_2.png"}
        loading="lazy"
        alt={"Polygon 2"}
      />
      <Polygon3
        src={"/Points_Polygon_3.png"}
        loading="lazy"
        alt={"Polygon 3"}
      />
      <Polygon4
        src={"/Points_Polygon_4.png"}
        loading="lazy"
        alt={"Polygon 4"}
      />
      <Polygon5
        src={"/Points_Polygon_5.png"}
        loading="lazy"
        alt={"Polygon 5"}
      />
      <Polygon6
        src={"/Points_Polygon_6.png"}
        loading="lazy"
        alt={"Polygon 6"}
      />
      <Polygon6
        src={"/Points_Polygon_6.png"}
        loading="lazy"
        alt={"Polygon 6"}
      />
    </Points1>
  );
}

export default Points;
