/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
// import Rectangle3463891Image from "src/assets/images/Screen1bottom_Rectangle_3463891.png";
// import Vector16Image from "src/assets/images/Screen1bottom_Vector_16.png";
// import Polygon1Image from "src/assets/images/Screen1bottom_Polygon_1.png";
import { styled } from "@mui/material/styles";

const Screen1Bottom1 = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `747.02px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle3463891 = styled("img")({
  height: `287.91px`,
  width: `673.33px`,
  position: `absolute`,
  left: `57px`,
  top: `220px`,
});

const Vector16 = styled("img")({
  height: `193.64px`,
  width: `572.84px`,
  position: `absolute`,
  left: `103px`,
  top: `258px`,
});

const H1 = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(24, 23, 37, 1)`,
  fontStyle: `normal`,
  fontSize: `20px`,
  letterSpacing: `0.10000000149011612px`,
  textDecoration: `none`,
  lineHeight: `28.5px`,
  textTransform: `none`,
  width: `317px`,
  position: `absolute`,
  left: `356px`,
  top: `287px`,
});

const Polygon1 = styled("img")({
  height: `85px`,
  width: `85px`,
  position: `absolute`,
  left: `257px`,
  top: `273px`,
});

function Screen1Bottom(props) {
  return (
    <Screen1Bottom1 className={props.className}>
      <Rectangle3463891
        src={"/Screen1bottom_Rectangle_3463891.png"}
        loading="lazy"
        alt={"Rectangle 3463891"}
      />
      <Vector16
        src={"/Screen1bottom_Vector_16.png"}
        loading="lazy"
        alt={"Vector 16"}
      />
      <H1>
        {`Unlock your reward
after purchase!`}
      </H1>
      <Polygon1
        src={"/Screen1bottom_Polygon_1.png"}
        loading="lazy"
        alt={"Polygon 1"}
      />
    </Screen1Bottom1>
  );
}

export default Screen1Bottom;
